#!/bin/bash
# rm -rf data/results/*/*
# rm -rf data/output/*/*
make
for j in {0..3}
do
    for i in {1..7}
    do
        ./build/coder/coder "data/input/testy4/example$j.tga" "data/output/test$j/var$i" "$i"
        ./build/decoder/decoder "data/output/test$j/var$i" "data/results/test$j/var$i"
        ./build/statsChecker/statsChecker "data/input/testy4/example$j.tga" "data/results/test$j/var$i" > "data/sc/test$j/var$i"
    done
done